<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\ReturnManagement\Enums;

/**
 *
 */
class RefundFeeType
{
    const C_ORIGINAL_SHIPPING = 'ORIGINAL_SHIPPING';
    const C_OTHER = 'OTHER';
    const C_PURCHASE_PRICE = 'PURCHASE_PRICE';
    const C_RESTOCKING_FEE = 'RESTOCKING_FEE';
}
