<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\ReturnManagement\Enums;

class UserFilterRoleType
{
    const C_BUYER = 'BUYER';
    const C_BUYERORSELLER = 'BUYERORSELLER';
    const C_SELLER = 'SELLER';
}
