<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\Trading\Enums;

/**
 *
 */
class AttributeConversionEnabledCodeType
{
    const C_CUSTOM_CODE = 'CustomCode';
    const C_DISABLED = 'Disabled';
    const C_ENABLED = 'Enabled';
    const C_NOT_APPLICABLE = 'NotApplicable';
}
