<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\Trading\Enums;

/**
 *
 */
class CommentTypeCodeType
{
    const C_CUSTOM_CODE = 'CustomCode';
    const C_INDEPENDENTLY_WITHDRAWN = 'IndependentlyWithdrawn';
    const C_NEGATIVE = 'Negative';
    const C_NEUTRAL = 'Neutral';
    const C_POSITIVE = 'Positive';
    const C_WITHDRAWN = 'Withdrawn';
}
