<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\Trading\Enums;

/**
 *
 */
class MailOptionsTypeCodeType
{
    const C_CUSTOM_CODE = 'CustomCode';
    const C_DO_NOT_SEND_EMAIL = 'DoNotSendEmail';
    const C_EMAIL_COPY_TO_SENDER = 'EmailCopyToSender';
    const C_HIDE_SENDER_EMAIL_ADDRESS = 'HideSenderEmailAddress';
}
