<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\Trading\Enums;

/**
 *
 */
class MessageTypeCodeType
{
    const C_ALL = 'All';
    const C_ASK_SELLER_QUESTION = 'AskSellerQuestion';
    const C_CLASSIFIEDS_BEST_OFFER = 'ClassifiedsBestOffer';
    const C_CLASSIFIEDS_CONTACT_SELLER = 'ClassifiedsContactSeller';
    const C_CONTACTE_BAY_MEMBER_VIA_ANONYMOUS_EMAIL = 'ContacteBayMemberViaAnonymousEmail';
    const C_CONTACTE_BAY_MEMBER_VIA_COMMUNITY_LINK = 'ContacteBayMemberViaCommunityLink';
    const C_CONTACT_EBAY_MEMBER = 'ContactEbayMember';
    const C_CONTACT_MY_BIDDER = 'ContactMyBidder';
    const C_CONTACT_TRANSACTION_PARTNER = 'ContactTransactionPartner';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_RESPONSE_TOASQ_QUESTION = 'ResponseToASQQuestion';
    const C_RESPONSE_TO_CONTACTE_BAY_MEMBER = 'ResponseToContacteBayMember';
}
