<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\Trading\Enums;

/**
 *
 */
class PromotionSchemeCodeType
{
    const C_CATEGORY_PROXIMITY = 'CategoryProximity';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_DEFAULT_CROSS_SELL_LOGIC = 'DefaultCrossSellLogic';
    const C_DEFAULT_RULE = 'DefaultRule';
    const C_DEFAULT_UP_SELL_LOGIC = 'DefaultUpSellLogic';
    const C_ITEM_TO_DEFAULT_RULE = 'ItemToDefaultRule';
    const C_ITEM_TO_ITEM = 'ItemToItem';
    const C_ITEM_TO_STORE_CAT = 'ItemToStoreCat';
    const C_RELATED_CATEGORY_RULE = 'RelatedCategoryRule';
    const C_STORE_TO_STORE_CAT = 'StoreToStoreCat';
}
