<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\Trading\Enums;

/**
 *
 */
class RCSPaymentStatusCodeType
{
    const C_CANCELED = 'Canceled';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_PAID = 'Paid';
    const C_PENDING = 'Pending';
}
