<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\Trading\Enums;

/**
 *
 */
class SellerLevelCodeType
{
    const C_BRONZE = 'Bronze';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_GOLD = 'Gold';
    const C_NONE = 'None';
    const C_PLATINUM = 'Platinum';
    const C_SILVER = 'Silver';
    const C_TITANIUM = 'Titanium';
}
