<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\Trading\Enums;

/**
 *
 */
class ShippingServiceType
{
    const C_DOMESTIC = 'Domestic';
    const C_INTERNATIONAL = 'International';
}
