<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\Trading\Enums;

/**
 *
 */
class URLTypeCodeType
{
    const C_CUSTOM_CODE = 'CustomCode';
    const C_E_BAY_STOREURL = 'eBayStoreURL';
    const C_LARGE_LOGOURL = 'LargeLogoURL';
    const C_MEDIUM_LOGOURL = 'MediumLogoURL';
    const C_MYE_BAYURL = 'MyeBayURL';
    const C_MYE_BAY_BIDDINGURL = 'MyeBayBiddingURL';
    const C_MYE_BAY_NOT_WONURL = 'MyeBayNotWonURL';
    const C_MYE_BAY_WATCHINGURL = 'MyeBayWatchingURL';
    const C_MYE_BAY_WONURL = 'MyeBayWonURL';
    const C_SMALL_LOGOURL = 'SmallLogoURL';
    const C_VIEW_ITEMURL = 'ViewItemURL';
    const C_VIEW_USERURL = 'ViewUserURL';
}
