<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\FileTransfer\Enums;

/**
 *
 */
class ErrorSeverity
{
    const C_ERROR = 'Error';
    const C_WARNING = 'Warning';
}
