<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Shopping\Enums;

class SiteCodeType
{
    const C_AUSTRALIA = 'Australia';
    const C_AUSTRIA = 'Austria';
    const C_BELGIUM__DUTCH = 'Belgium_Dutch';
    const C_BELGIUM__FRENCH = 'Belgium_French';
    const C_CANADA = 'Canada';
    const C_CANADA_FRENCH = 'CanadaFrench';
    const C_CHINA = 'China';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_E_BAY_MOTORS = 'eBayMotors';
    const C_FRANCE = 'France';
    const C_GERMANY = 'Germany';
    const C_HONG_KONG = 'HongKong';
    const C_INDIA = 'India';
    const C_IRELAND = 'Ireland';
    const C_ITALY = 'Italy';
    const C_MALAYSIA = 'Malaysia';
    const C_NETHERLANDS = 'Netherlands';
    const C_PHILIPPINES = 'Philippines';
    const C_POLAND = 'Poland';
    const C_RUSSIA = 'Russia';
    const C_SINGAPORE = 'Singapore';
    const C_SPAIN = 'Spain';
    const C_SWEDEN = 'Sweden';
    const C_SWITZERLAND = 'Switzerland';
    const C_TAIWAN = 'Taiwan';
    const C_UK = 'UK';
    const C_US = 'US';
}
