<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Marketing\Enums;

class CampaignStatusEnum
{
    const C_DELETED = 'DELETED';
    const C_ENDED = 'ENDED';
    const C_ENDING_SOON = 'ENDING_SOON';
    const C_PAUSED = 'PAUSED';
    const C_PENDING = 'PENDING';
    const C_RUNNING = 'RUNNING';
    const C_SCHEDULED = 'SCHEDULED';
}
