<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Marketing\Enums;

class CriterionTypeEnum
{
    const C_INVENTORY_PARTITION = 'INVENTORY_PARTITION';
}
