<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Marketing\Enums;

class PromotionStatusEnum
{
    const C_DRAFT = 'DRAFT';
    const C_ENDED = 'ENDED';
    const C_INVALID = 'INVALID';
    const C_PAUSED = 'PAUSED';
    const C_RUNNING = 'RUNNING';
    const C_SCHEDULED = 'SCHEDULED';
}
