<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Browse\Enums;

class DeliveryOptionsEnum
{
    const C_DIGITAL_DELIVERY = 'DIGITAL_DELIVERY';
    const C_IN_STORE_PICKUP = 'IN_STORE_PICKUP';
    const C_PICKUP_DROP_OFF = 'PICKUP_DROP_OFF';
    const C_SELLER_ARRANGED_LOCAL_PICKUP = 'SELLER_ARRANGED_LOCAL_PICKUP';
    const C_SHIP_TO_HOME = 'SHIP_TO_HOME';
}
