<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\Browse\Enums;

/**
 *
 */
class PriceDisplayConditionEnum
{
    const C_ALWAYS_SHOW = 'ALWAYS_SHOW';
    const C_ONLY_SHOW_WHEN_ADDED_IN_CART = 'ONLY_SHOW_WHEN_ADDED_IN_CART';
}
