<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Inventory\Enums;

class FormatTypeEnum
{
    const C_FIXED_PRICE = 'FIXED_PRICE';
}
