<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\ResolutionCaseManagement\Enums;

/**
 *
 */
class ProofType
{
    const C_OTHER = 'OTHER';
    const C_PROOF_OF_REFUND = 'PROOF_OF_REFUND';
    const C_PROOF_OF_SHIPPING = 'PROOF_OF_SHIPPING';
}
