<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\ResolutionCaseManagement\Enums;

class SellerINREscalationReasonType
{
    const C_BUYER_STILL_UNHAPPY_AFTER_REFUND = 'BUYER_STILL_UNHAPPY_AFTER_REFUND';
    const C_ITEM_SHIPPED_WITH_TRACKING = 'ITEM_SHIPPED_WITH_TRACKING';
    const C_OTHER = 'OTHER';
    const C_TROUBLE_COMMUNICATION_WITH_BUYER = 'TROUBLE_COMMUNICATION_WITH_BUYER';
}
