<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\ResolutionCaseManagement\Enums;

/**
 *
 */
class UPICaseStatusType
{
    const C_CLOSED = 'CLOSED';
    const C_CLOSED_FVFCREDIT_NOSTRIKE = 'CLOSED_FVFCREDIT_NOSTRIKE';
    const C_CLOSED_FVFCREDIT_STRIKE = 'CLOSED_FVFCREDIT_STRIKE';
    const C_CLOSED_NOFVFCREDIT_NOSTRIKE = 'CLOSED_NOFVFCREDIT_NOSTRIKE';
    const C_CLOSED_NOFVFCREDIT_STRIKE = 'CLOSED_NOFVFCREDIT_STRIKE';
    const C_CS_CLOSED = 'CS_CLOSED';
    const C_EXPIRED = 'EXPIRED';
    const C_MY_PAYMENT_DUE = 'MY_PAYMENT_DUE';
    const C_MY_RESPONSE_DUE = 'MY_RESPONSE_DUE';
    const C_OTHER = 'OTHER';
    const C_OTHER_PARTY_RESPONSE_DUE = 'OTHER_PARTY_RESPONSE_DUE';
}
