<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

class AddressAttributeCodeType
{
    const C_CUSTOM_CODE = 'CustomCode';
    const C_REFERENCE_NUMBER = 'ReferenceNumber';
}
