<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

class DiscountNameCodeType
{
    const C_COMBINED_ITEM_WEIGHT = 'CombinedItemWeight';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_EACH_ADDITIONAL_AMOUNT = 'EachAdditionalAmount';
    const C_EACH_ADDITIONAL_AMOUNT_OFF = 'EachAdditionalAmountOff';
    const C_EACH_ADDITIONAL_PERCENT_OFF = 'EachAdditionalPercentOff';
    const C_INDIVIDUAL_ITEM_WEIGHT = 'IndividualItemWeight';
    const C_MAXIMUM_SHIPPING_COST_PER_ORDER = 'MaximumShippingCostPerOrder';
    const C_SHIPPING_COSTX_FOR_AMOUNTY = 'ShippingCostXForAmountY';
    const C_SHIPPING_COSTX_FOR_ITEM_COUNTN = 'ShippingCostXForItemCountN';
    const C_WEIGHT_OFF = 'WeightOff';
}
