<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

/**
 *
 */
class PictureWatermarkCodeType
{
    const C_CUSTOM_CODE = 'CustomCode';
    const C_ICON = 'Icon';
    const C_USER = 'User';
}
