<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

class TransactionReferenceCodeType
{
    const C_CUSTOM_CODE = 'CustomCode';
    const C_EXTERNAL_TRANSACTIONID = 'ExternalTransactionID';
    const C_MANDATE_REFERENCE_NUMBER = 'MandateReferenceNumber';
}
