<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class DisputeActivityCodeType
{
    const C_CAME_TO_AGREEMENT_NEEDFVF_CREDIT = 'CameToAgreementNeedFVFCredit';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_MUTUAL_AGREEMENT_OR_NO_BUYER_RESPONSE = 'MutualAgreementOrNoBuyerResponse';
    const C_SELLER_ADD_INFORMATION = 'SellerAddInformation';
    const C_SELLER_COMMENT = 'SellerComment';
    const C_SELLER_COMPLETED_TRANSACTION = 'SellerCompletedTransaction';
    const C_SELLER_END_COMMUNICATION = 'SellerEndCommunication';
    const C_SELLER_OFFERS_REFUND = 'SellerOffersRefund';
    const C_SELLER_PAYMENT_NOT_RECEIVED = 'SellerPaymentNotReceived';
    const C_SELLER_SHIPPED_ITEM = 'SellerShippedItem';
}
