<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\Trading\Enums;

/**
 *
 */
class FedExRateOptionCodeType
{
    const C_CUSTOM_CODE = 'CustomCode';
    const C_FED_EX_COUNTER = 'FedExCounter';
    const C_FED_EX_DISCOUNTED = 'FedExDiscounted';
    const C_FED_EX_STANDARD_LIST = 'FedExStandardList';
}
