<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class FeedbackTypeCodeType
{
    const C_CUSTOM_CODE = 'CustomCode';
    const C_FEEDBACK_LEFT = 'FeedbackLeft';
    const C_FEEDBACK_RECEIVED = 'FeedbackReceived';
    const C_FEEDBACK_RECEIVED_AS_BUYER = 'FeedbackReceivedAsBuyer';
    const C_FEEDBACK_RECEIVED_AS_SELLER = 'FeedbackReceivedAsSeller';
}
