<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class FlatRateInsuranceRangeCodeType
{
    const C_CUSTOM_CODE = 'CustomCode';
    const C_FLAT_RATE_INSURANCE_RANGE1 = 'FlatRateInsuranceRange1';
    const C_FLAT_RATE_INSURANCE_RANGE2 = 'FlatRateInsuranceRange2';
    const C_FLAT_RATE_INSURANCE_RANGE3 = 'FlatRateInsuranceRange3';
    const C_FLAT_RATE_INSURANCE_RANGE4 = 'FlatRateInsuranceRange4';
    const C_FLAT_RATE_INSURANCE_RANGE5 = 'FlatRateInsuranceRange5';
    const C_FLAT_RATE_INSURANCE_RANGE6 = 'FlatRateInsuranceRange6';
}
