<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\Trading\Enums;

/**
 *
 */
class MerchDisplayCodeType
{
    const C_CUSTOM_CODE = 'CustomCode';
    const C_DEFAULT_THEME = 'DefaultTheme';
    const C_STORE_THEME = 'StoreTheme';
}
