<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class PaymentMethodSearchCodeType
{
    const C_CUSTOM_CODE = 'CustomCode';
    const C_PAISA_PAY = 'PaisaPay';
    const C_PAISA_PAY_ESCROWEMI = 'PaisaPayEscrowEMI';
    const C_PAY_PAL = 'PayPal';
    const C_PAY_PAL_OR_PAISA_PAY = 'PayPalOrPaisaPay';
}
