<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class ProfileCategoryGroupCodeType
{
    const C_ALL = 'ALL';
    const C_INHERIT = 'Inherit';
    const C_MOTORS_VEHICLE = 'MOTORS_VEHICLE';
    const C_NONE = 'None';
}
