<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\Trading\Enums;

/**
 *
 */
class PromotionalSaleTypeCodeType
{
    const C_CUSTOM_CODE = 'CustomCode';
    const C_FREE_SHIPPING_ONLY = 'FreeShippingOnly';
    const C_PRICE_DISCOUNT_AND_FREE_SHIPPING = 'PriceDiscountAndFreeShipping';
    const C_PRICE_DISCOUNT_ONLY = 'PriceDiscountOnly';
}
