<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class ReasonHideFromSearchCodeType
{
    const C_DUPLICATE_LISTING = 'DuplicateListing';
    const C_OUT_OF_STOCK = 'OutOfStock';
}
