<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class RecommendationEngineCodeType
{
    const C_CUSTOM_CODE = 'CustomCode';
    const C_ITEM_SPECIFICS = 'ItemSpecifics';
    const C_LISTING_ANALYZER = 'ListingAnalyzer';
    const C_PRODUCT_PRICING = 'ProductPricing';
    const C_SIFFTAS = 'SIFFTAS';
    const C_SUGGESTED_ATTRIBUTES = 'SuggestedAttributes';
}
