<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\Trading\Enums;

/**
 *
 */
class RestockingFeeCodeType
{
    const C_CUSTOM_CODE = 'CustomCode';
    const C_NO_RESTOCKING_FEE = 'NoRestockingFee';
    const C_PERCENT_10 = 'Percent_10';
    const C_PERCENT_15 = 'Percent_15';
    const C_PERCENT_20 = 'Percent_20';
    const C_PERCENT_25 = 'Percent_25';
}
