<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Trading\Enums;

class SellingManagerAutoSecondChanceOfferTypeCodeType
{
    const C_BIDS_GREATER_THAN_AMOUNT = 'BidsGreaterThanAmount';
    const C_BIDS_GREATER_THAN_COST_PLUS_AMOUNT = 'BidsGreaterThanCostPlusAmount';
    const C_BIDS_GREATER_THAN_COST_PLUS_PERCENTAGE = 'BidsGreaterThanCostPlusPercentage';
    const C_CUSTOM_CODE = 'CustomCode';
}
