<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\Trading\Enums;

/**
 *
 */
class UserStatusCodeType
{
    const C_ACCOUNT_ON_HOLD = 'AccountOnHold';
    const C_CONFIRMED = 'Confirmed';
    const C_CREDIT_CARD_VERIFY = 'CreditCardVerify';
    const C_CREDIT_CARD_VERIFY_HALF_OPT_IN = 'CreditCardVerifyHalfOptIn';
    const C_CREDIT_CARD_VERIFY_PASSPORT = 'CreditCardVerifyPassport';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_DELETED = 'Deleted';
    const C_GHOST = 'Ghost';
    const C_GUEST = 'Guest';
    const C_IN_MAINTENANCE = 'InMaintenance';
    const C_MERGED = 'Merged';
    const C_REGISTRATION_CODE_MAIL_OUT = 'RegistrationCodeMailOut';
    const C_SUSPENDED = 'Suspended';
    const C_TERM_PENDING = 'TermPending';
    const C_UNCONFIRMED = 'Unconfirmed';
    const C_UNCONFIRMED_EXPRESS = 'UnconfirmedExpress';
    const C_UNCONFIRMED_HALF_OPT_IN = 'UnconfirmedHalfOptIn';
    const C_UNCONFIRMED_PASSPORT = 'UnconfirmedPassport';
    const C_UNKNOWN = 'Unknown';
}
