<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

/**
 *
 */
class AddressTypeEnum
{
    const C_BUSINESS = 'BUSINESS';
    const C_PO_BOX = 'PO_BOX';
    const C_RESIDENCE = 'RESIDENCE';
}
