<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

class CaseStatusEnum
{
    const C_CLOSED = 'CLOSED';
    const C_CS_CLOSED = 'CS_CLOSED';
    const C_ON_HOLD = 'ON_HOLD';
    const C_OPEN = 'OPEN';
    const C_OTHER = 'OTHER';
    const C_REFUND_AGREED_BUT_FAILED = 'REFUND_AGREED_BUT_FAILED';
    const C_WAITING_CS = 'WAITING_CS';
    const C_WAITING_DELIVERY = 'WAITING_DELIVERY';
}
