<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

class LanguageScriptEnum
{
    const C_ARABIC = 'ARABIC';
    const C_ARMENIAN = 'ARMENIAN';
    const C_CHINESE = 'CHINESE';
    const C_CYRILLIC = 'CYRILLIC';
    const C_GEORGIAN = 'GEORGIAN';
    const C_GREEK = 'GREEK';
    const C_HEBREW = 'HEBREW';
    const C_INDIC = 'INDIC';
    const C_JAPANESE = 'JAPANESE';
    const C_KOREAN = 'KOREAN';
    const C_LATIN = 'LATIN';
    const C_THAI = 'THAI';
}
