<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

/**
 *
 */
class LanguageEnum
{
    const C_DE = 'de';
    const C_EL = 'el';
    const C_EN = 'en';
    const C_EO = 'eo';
    const C_ES = 'es';
    const C_FR = 'fr';
    const C_HY = 'hy';
    const C_IT = 'it';
    const C_JA = 'ja';
    const C_KA = 'ka';
    const C_NL = 'nl';
    const C_PT = 'pt';
    const C_RU = 'ru';
    const C_SV = 'sv';
    const C_TR = 'tr';
    const C_XX = 'xx';
}
