<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

class PaymentDenialReasonEnum
{
    const C_OTHER = 'OTHER';
    const C_PP_ACH_RETURN = 'PP_ACH_RETURN';
    const C_PP_ADMINISTRATIVE_FRAUD_REVIEW = 'PP_ADMINISTRATIVE_FRAUD_REVIEW';
    const C_PP_CREDITCARD_CHARGEBACK = 'PP_CREDITCARD_CHARGEBACK';
    const C_PP_DISALLOWED_DISPUTE = 'PP_DISALLOWED_DISPUTE';
    const C_PP_ELV_REVERSAL = 'PP_ELV_REVERSAL';
    const C_PP_PAYPAL_GUEST = 'PP_PAYPAL_GUEST';
    const C_PP_UNAUTHORIZED_TRANSACTION = 'PP_UNAUTHORIZED_TRANSACTION';
}
