<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

class PaymentStatusEnum
{
    const C_MARK_AS_PAID = 'MARK_AS_PAID';
    const C_NOT_PAID = 'NOT_PAID';
    const C_PAYPAL_PAID = 'PAYPAL_PAID';
    const C_UNKNOWN = 'UNKNOWN';
}
