<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

class PaymentProviderEnum
{
    const C_PAYPAL = 'PAYPAL';
    const C_UNKNOWN = 'UNKNOWN';
}
