<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

/**
 *
 */
class ReturnTypeEnum
{
    const C_CANCEL = 'CANCEL';
    const C_MONEY_BACK = 'MONEY_BACK';
    const C_REPLACEMENT = 'REPLACEMENT';
    const C_UNKNOWN = 'UNKNOWN';
}
