<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\PostOrder\Enums;

class UserPartyEnum
{
    const C_BUYER = 'BUYER';
    const C_CSR = 'CSR';
    const C_SELLER = 'SELLER';
    const C_SYSTEM = 'SYSTEM';
    const C_UNKNOWN = 'UNKNOWN';
}
