<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\Order\Enums;

/**
 *
 */
class PaymentMethodBrandEnum
{
    const C_AMERICAN_EXPRESS = 'AMERICAN_EXPRESS';
    const C_DISCOVER = 'DISCOVER';
    const C_MASTERCARD = 'MASTERCARD';
    const C_VISA = 'VISA';
}
