<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\HalfFinding\Enums;

class ItemFilterType
{
    const C_CONDITION = 'Condition';
    const C_EXCLUDE_SELLER = 'ExcludeSeller';
    const C_FEEDBACK_SCORE_MIN = 'FeedbackScoreMin';
    const C_LISTING_TYPE = 'ListingType';
    const C_MAX_PRICE = 'MaxPrice';
    const C_SELLER = 'Seller';
    const C_SHIPPING_SERVICE = 'ShippingService';
}
