<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

/**
 *
 */
class ListingStatusCodeType
{
    const C_ACTIVE = 'Active';
    const C_COMPLETED = 'Completed';
    const C_CUSTOM = 'Custom';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_ENDED = 'Ended';
}
