<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

/**
 *
 */
class MeasurementSystemCodeType
{
    const C_ENGLISH = 'English';
    const C_METRIC = 'Metric';
}
