<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

/**
 *
 */
class PictureUploadPolicyCodeType
{
    const C_ADD = 'Add';
    const C_CLEAR_AND_ADD = 'ClearAndAdd';
    const C_CUSTOM_CODE = 'CustomCode';
}
