<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

/**
 *
 */
class PromotionItemPriceTypeCodeType
{
    const C_AUCTION_PRICE = 'AuctionPrice';
    const C_BEST_OFFER_ONLY_PRICE = 'BestOfferOnlyPrice';
    const C_BUY_IT_NOW_PRICE = 'BuyItNowPrice';
    const C_CLASSIFIED_AD_PRICE = 'ClassifiedAdPrice';
}
