<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

/**
 *
 */
class ReasonHideFromSearchCodeType
{
    const C_DUPLICATE_LISTING = 'DuplicateListing';
    const C_OUT_OF_STOCK = 'OutOfStock';
}
