<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\MerchantData\Enums;

/**
 *
 */
class SellerPaymentMethodCodeType
{
    const C_CREDIT_CARD = 'CreditCard';
    const C_CUSTOM_CODE = 'CustomCode';
    const C_DIRECT_DEBIT = 'DirectDebit';
    const C_DIRECT_DEBIT_PENDING_SIGNATURE_MANDATE = 'DirectDebitPendingSignatureMandate';
    const C_DIRECT_DEBIT_PENDING_VERIFICATION = 'DirectDebitPendingVerification';
    const C_E_BAY_DIRECT_PAY = 'eBayDirectPay';
    const C_NOTHING_ON_FILE = 'NothingOnFile';
    const C_PAY_PAL = 'PayPal';
}
