<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\Test\Account\Types;

use DTS\eBaySDK\Account\Types\OptOutOfProgramRestRequest;

class OptOutOfProgramRestRequestTest extends \PHPUnit_Framework_TestCase
{
    private $obj;

    protected function setUp()
    {
        $this->obj = new OptOutOfProgramRestRequest();
    }

    public function testCanBeCreated()
    {
        $this->assertInstanceOf('\DTS\eBaySDK\Account\Types\OptOutOfProgramRestRequest', $this->obj);
    }

    public function testExtendsProgram()
    {
        $this->assertInstanceOf('\DTS\eBaySDK\Account\Types\Program', $this->obj);
    }
}
