<?php
/**
 * The contents of this file was generated using the WSDLs as provided by eBay.
 *
 * DO NOT EDIT THIS FILE!
 */

namespace DTS\eBaySDK\MerchantData\Types;

/**
 *
 * @property string $PictureName
 * @property integer $PictureSystemVersion
 * @property \DTS\eBaySDK\MerchantData\Enums\PictureSetCodeType $PictureSet
 * @property \DTS\eBaySDK\MerchantData\Types\Base64BinaryType $PictureData
 * @property \DTS\eBaySDK\MerchantData\Enums\PictureUploadPolicyCodeType $PictureUploadPolicy
 * @property string[] $ExternalPictureURL
 * @property integer $ExtensionInDays
 */
class UploadSiteHostedPicturesRequestType extends \DTS\eBaySDK\MerchantData\Types\AbstractRequestType
{
    /**
     * @var array Properties belonging to objects of this class.
     */
    private static $propertyTypes = [
        'PictureName' => [
            'type' => 'string',
            'unbound' => false,
            'attribute' => false,
            'elementName' => 'PictureName'
        ],
        'PictureSystemVersion' => [
            'type' => 'integer',
            'unbound' => false,
            'attribute' => false,
            'elementName' => 'PictureSystemVersion'
        ],
        'PictureSet' => [
            'type' => 'string',
            'unbound' => false,
            'attribute' => false,
            'elementName' => 'PictureSet'
        ],
        'PictureData' => [
            'type' => 'DTS\eBaySDK\MerchantData\Types\Base64BinaryType',
            'unbound' => false,
            'attribute' => false,
            'elementName' => 'PictureData'
        ],
        'PictureUploadPolicy' => [
            'type' => 'string',
            'unbound' => false,
            'attribute' => false,
            'elementName' => 'PictureUploadPolicy'
        ],
        'ExternalPictureURL' => [
            'type' => 'string',
            'unbound' => true,
            'attribute' => false,
            'elementName' => 'ExternalPictureURL'
        ],
        'ExtensionInDays' => [
            'type' => 'integer',
            'unbound' => false,
            'attribute' => false,
            'elementName' => 'ExtensionInDays'
        ]
    ];

    /**
     * @param array $values Optional properties and values to assign to the object.
     */
    public function __construct(array $values = [])
    {
        list($parentValues, $childValues) = self::getParentValues(self::$propertyTypes, $values);

        parent::__construct($parentValues);

        if (!array_key_exists(__CLASS__, self::$properties)) {
            self::$properties[__CLASS__] = array_merge(self::$properties[get_parent_class()], self::$propertyTypes);
        }

        if (!array_key_exists(__CLASS__, self::$xmlNamespaces)) {
            self::$xmlNamespaces[__CLASS__] = 'xmlns="urn:ebay:apis:eBLBaseComponents"';
        }

        if (!array_key_exists(__CLASS__, self::$requestXmlRootElementNames)) {
            self::$requestXmlRootElementNames[__CLASS__] = 'UploadSiteHostedPicturesRequest';
        }

        $this->setValues(__CLASS__, $childValues);
    }
}
