<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Analytics\Enums;

class CycleTypeEnum
{
    const C_CURRENT = 'CURRENT';
    const C_PROJECTED = 'PROJECTED';
}
