<?php
/**
 * DO NOT EDIT THIS FILE!
 *
 * This file was automatically generated from external sources.
 *
 * Any manual change here will be lost the next time the SDK
 * is updated. You've been warned!
 */

namespace DTS\eBaySDK\Analytics\Enums;

class ProgramEnum
{
    const C_PROGRAM_DE = 'PROGRAM_DE';
    const C_PROGRAM_GLOBAL = 'PROGRAM_GLOBAL';
    const C_PROGRAM_UK = 'PROGRAM_UK';
    const C_PROGRAM_US = 'PROGRAM_US';
}
